Started logging messages at Sat Aug 30 06:38:08 2014
Info:    Using UV tolerance 1e-006
Info:    Using UV tolerance 1e-006
Info:    HwNlibToTSLib options selected:
Info:        Points: Off
Info:        Curves: On
Info:        Surfaces: Off
Info:        BReps: On
Info:        Do not create IwAssembly/IwAssemblyInstance objects
Info:        Making untrimmed surfaces into BReps
Info:        Making solids into single BReps
Info:        Make components of failed trims
Info:        Make faces of failed B-reps
Info:    HW SAT v1.2.6-maint
Info:    Reading 
Info:    Processing 
Info:    Transferring 
Info:    
Info:    Found 0 points in file
Info:    Found 0 curves in file
Info:    Found 0 surfaces in file
Info:    Found 0 trimmed surfaces in file
Info:    Found 1 B-reps in file
Info:    Found 406 B-rep faces in file
Info:    
Info:    Using 3D tolerance 1e-006
Info:    Working on 0
Info:        Working on 58
Info:            Created 
Info:        Working on 59
Info:            Created 
Info:        Working on 75
Info:            Created 
Info:        Working on 77
Info:            Created 
Info:        Working on 6
Info:            Created 
Info:        Working on 73
Info:            Created 
Info:        Working on 93
Info:            Created 
Info:        Working on 9
Info:            Created 
Info:        Working on 91
Info:            Created 
Info:        Working on 110
Info:            Created 
Info:        Working on 13
Info:            Created 
Info:        Working on 21
Info:            Created 
Info:        Working on 38
Info:            Created 
Info:        Working on 161
Info:            Created 
Info:        Working on 162
Info:            Created 
Info:        Working on 249
Info:            Created 
Info:        Working on 251
Info:            Created 
Info:        Working on 62
Info:            Created 
Info:        Working on 222
Info:            Created 
Info:        Working on 335
Info:            Created 
Info:        Working on 85
Info:            Created 
Info:        Working on 221
Info:            Created 
Info:        Working on 406
Info:            Created 
Info:        Working on 105
Info:            Created 
Info:        Working on 130
Info:            Created 
Info:        Working on 173
Info:            Created 
Info:        Working on 217
Info:            Created 
Info:        Working on 218
Info:            Created 
Info:        Working on 404
Info:            Created 
Info:        Working on 405
Info:            Created 
Info:        Working on 241
Info:            Created 
Info:        Working on 297
Info:            Created 
Info:        Working on 509
Info:            Created 
Info:        Working on 331
Info:            Created 
Info:        Working on 294
Info:            Created 
Info:        Working on 506
Info:            Created 
Info:        Working on 430
Info:            Created 
Info:        Working on 397
Info:            Created 
Info:        Working on 507
Info:            Created 
Info:        Working on 285
Info:            Created 
Info:        Working on 286
Info:            Created 
Info:        Working on 501
Info:            Created 
Info:        Working on 502
Info:            Created 
Info:        Working on 390
Info:            Created 
Info:        Working on 383
Info:            Created 
Info:        Working on 609
Info:            Created 
Info:        Working on 498
Info:            Created 
Info:        Working on 379
Info:            Created 
Info:        Working on 606
Info:            Created 
Info:        Working on 604
Info:            Created 
Info:        Working on 493
Info:            Created 
Info:        Working on 607
Info:            Created 
Info:        Working on 370
Info:            Created 
Info:        Working on 371
Info:            Created 
Info:        Working on 600
Info:            Created 
Info:        Working on 601
Info:            Created 
Info:        Working on 485
Info:            Created 
Info:        Working on 478
Info:            Created 
Info:        Working on 719
Info:            Created 
Info:        Working on 597
Info:            Created 
Info:        Working on 474
Info:            Created 
Info:        Working on 716
Info:            Created 
Info:        Working on 714
Info:            Created 
Info:        Working on 592
Info:            Created 
Info:        Working on 717
Info:            Created 
Info:        Working on 465
Info:            Created 
Info:        Working on 466
Info:            Created 
Info:        Working on 710
Info:            Created 
Info:        Working on 711
Info:            Created 
Info:        Working on 584
Info:            Created 
Info:        Working on 577
Info:            Created 
Info:        Working on 851
Info:            Created 
Info:        Working on 707
Info:            Created 
Info:        Working on 573
Info:            Created 
Info:        Working on 848
Info:            Created 
Info:        Working on 846
Info:            Created 
Info:        Working on 702
Info:            Created 
Info:        Working on 849
Info:            Created 
Info:        Working on 564
Info:            Created 
Info:        Working on 565
Info:            Created 
Info:        Working on 842
Info:            Created 
Info:        Working on 843
Info:            Created 
Info:        Working on 694
Info:            Created 
Info:        Working on 687
Info:            Created 
Info:        Working on 1004
Info:            Created 
Info:        Working on 839
Info:            Created 
Info:        Working on 683
Info:            Created 
Info:        Working on 1001
Info:            Created 
Info:        Working on 999
Info:            Created 
Info:        Working on 834
Info:            Created 
Info:        Working on 1002
Info:            Created 
Info:        Working on 674
Info:            Created 
Info:        Working on 675
Info:            Created 
Info:        Working on 995
Info:            Created 
Info:        Working on 996
Info:            Created 
Info:        Working on 826
Info:            Created 
Info:        Working on 819
Info:            Created 
Info:        Working on 1170
Info:            Created 
Info:        Working on 992
Info:            Created 
Info:        Working on 815
Info:            Created 
Info:        Working on 1167
Info:            Created 
Info:        Working on 1165
Info:            Created 
Info:        Working on 987
Info:            Created 
Info:        Working on 1168
Info:            Created 
Info:        Working on 806
Info:            Created 
Info:        Working on 807
Info:            Created 
Info:        Working on 1161
Info:            Created 
Info:        Working on 1162
Info:            Created 
Info:        Working on 979
Info:            Created 
Info:        Working on 972
Info:            Created 
Info:        Working on 1339
Info:            Created 
Info:        Working on 1158
Info:            Created 
Info:        Working on 968
Info:            Created 
Info:        Working on 1336
Info:            Created 
Info:        Working on 1334
Info:            Created 
Info:        Working on 1153
Info:            Created 
Info:        Working on 1337
Info:            Created 
Info:        Working on 959
Info:            Created 
Info:        Working on 960
Info:            Created 
Info:        Working on 1330
Info:            Created 
Info:        Working on 1331
Info:            Created 
Info:        Working on 1145
Info:            Created 
Info:        Working on 1138
Info:            Created 
Info:        Working on 1509
Info:            Created 
Info:        Working on 1327
Info:            Created 
Info:        Working on 1134
Info:            Created 
Info:        Working on 1506
Info:            Created 
Info:        Working on 1504
Info:            Created 
Info:        Working on 1322
Info:            Created 
Info:        Working on 1507
Info:            Created 
Info:        Working on 1125
Info:            Created 
Info:        Working on 1126
Info:            Created 
Info:        Working on 1500
Info:            Created 
Info:        Working on 1501
Info:            Created 
Info:        Working on 1314
Info:            Created 
Info:        Working on 1307
Info:            Created 
Info:        Working on 1686
Info:            Created 
Info:        Working on 1497
Info:            Created 
Info:        Working on 1303
Info:            Created 
Info:        Working on 1683
Info:            Created 
Info:        Working on 1681
Info:            Created 
Info:        Working on 1492
Info:            Created 
Info:        Working on 1684
Info:            Created 
Info:        Working on 1294
Info:            Created 
Info:        Working on 1295
Info:            Created 
Info:        Working on 1677
Info:            Created 
Info:        Working on 1678
Info:            Created 
Info:        Working on 1484
Info:            Created 
Info:        Working on 1477
Info:            Created 
Info:        Working on 1868
Info:            Created 
Info:        Working on 1674
Info:            Created 
Info:        Working on 1473
Info:            Created 
Info:        Working on 1865
Info:            Created 
Info:        Working on 1863
Info:            Created 
Info:        Working on 1669
Info:            Created 
Info:        Working on 1866
Info:            Created 
Info:        Working on 1464
Info:            Created 
Info:        Working on 1465
Info:            Created 
Info:        Working on 1859
Info:            Created 
Info:        Working on 1860
Info:            Created 
Info:        Working on 1661
Info:            Created 
Info:        Working on 1654
Info:            Created 
Info:        Working on 2047
Info:            Created 
Info:        Working on 1856
Info:            Created 
Info:        Working on 1650
Info:            Created 
Info:        Working on 2044
Info:            Created 
Info:        Working on 2042
Info:            Created 
Info:        Working on 1851
Info:            Created 
Info:        Working on 2045
Info:            Created 
Info:        Working on 1641
Info:            Created 
Info:        Working on 1642
Info:            Created 
Info:        Working on 2038
Info:            Created 
Info:        Working on 2039
Info:            Created 
Info:        Working on 1843
Info:            Created 
Info:        Working on 1836
Info:            Created 
Info:        Working on 2219
Info:            Created 
Info:        Working on 2035
Info:            Created 
Info:        Working on 1832
Info:            Created 
Info:        Working on 2216
Info:            Created 
Info:        Working on 2214
Info:            Created 
Info:        Working on 2030
Info:            Created 
Info:        Working on 2217
Info:            Created 
Info:        Working on 1823
Info:            Created 
Info:        Working on 1824
Info:            Created 
Info:        Working on 2210
Info:            Created 
Info:        Working on 2211
Info:            Created 
Info:        Working on 2022
Info:            Created 
Info:        Working on 2015
Info:            Created 
Info:        Working on 2389
Info:            Created 
Info:        Working on 2207
Info:            Created 
Info:        Working on 2011
Info:            Created 
Info:        Working on 2386
Info:            Created 
Info:        Working on 2384
Info:            Created 
Info:        Working on 2202
Info:            Created 
Info:        Working on 2387
Info:            Created 
Info:        Working on 2002
Info:            Created 
Info:        Working on 2003
Info:            Created 
Info:        Working on 2380
Info:            Created 
Info:        Working on 2381
Info:            Created 
Info:        Working on 2194
Info:            Created 
Info:        Working on 2187
Info:            Created 
Info:        Working on 2566
Info:            Created 
Info:        Working on 2377
Info:            Created 
Info:        Working on 2183
Info:            Created 
Info:        Working on 2563
Info:            Created 
Info:        Working on 2561
Info:            Created 
Info:        Working on 2372
Info:            Created 
Info:        Working on 2564
Info:            Created 
Info:        Working on 2174
Info:            Created 
Info:        Working on 2175
Info:            Created 
Info:        Working on 2557
Info:            Created 
Info:        Working on 2558
Info:            Created 
Info:        Working on 2364
Info:            Created 
Info:        Working on 2357
Info:            Created 
Info:        Working on 2748
Info:            Created 
Info:        Working on 2554
Info:            Created 
Info:        Working on 2353
Info:            Created 
Info:        Working on 2745
Info:            Created 
Info:        Working on 2743
Info:            Created 
Info:        Working on 2549
Info:            Created 
Info:        Working on 2746
Info:            Created 
Info:        Working on 2344
Info:            Created 
Info:        Working on 2345
Info:            Created 
Info:        Working on 2739
Info:            Created 
Info:        Working on 2740
Info:            Created 
Info:        Working on 2541
Info:            Created 
Info:        Working on 2534
Info:            Created 
Info:        Working on 2927
Info:            Created 
Info:        Working on 2736
Info:            Created 
Info:        Working on 2530
Info:            Created 
Info:        Working on 2924
Info:            Created 
Info:        Working on 2922
Info:            Created 
Info:        Working on 2731
Info:            Created 
Info:        Working on 2925
Info:            Created 
Info:        Working on 2521
Info:            Created 
Info:        Working on 2522
Info:            Created 
Info:        Working on 2918
Info:            Created 
Info:        Working on 2919
Info:            Created 
Info:        Working on 2723
Info:            Created 
Info:        Working on 2716
Info:            Created 
Info:        Working on 3099
Info:            Created 
Info:        Working on 2915
Info:            Created 
Info:        Working on 2712
Info:            Created 
Info:        Working on 3096
Info:            Created 
Info:        Working on 3094
Info:            Created 
Info:        Working on 2910
Info:            Created 
Info:        Working on 3097
Info:            Created 
Info:        Working on 2703
Info:            Created 
Info:        Working on 2704
Info:            Created 
Info:        Working on 3090
Info:            Created 
Info:        Working on 3091
Info:            Created 
Info:        Working on 2902
Info:            Created 
Info:        Working on 2895
Info:            Created 
Info:        Working on 3269
Info:            Created 
Info:        Working on 3087
Info:            Created 
Info:        Working on 2891
Info:            Created 
Info:        Working on 3266
Info:            Created 
Info:        Working on 3264
Info:            Created 
Info:        Working on 3082
Info:            Created 
Info:        Working on 3267
Info:            Created 
Info:        Working on 2882
Info:            Created 
Info:        Working on 2883
Info:            Created 
Info:        Working on 3260
Info:            Created 
Info:        Working on 3261
Info:            Created 
Info:        Working on 3074
Info:            Created 
Info:        Working on 3067
Info:            Created 
Info:        Working on 3446
Info:            Created 
Info:        Working on 3257
Info:            Created 
Info:        Working on 3063
Info:            Created 
Info:        Working on 3443
Info:            Created 
Info:        Working on 3441
Info:            Created 
Info:        Working on 3252
Info:            Created 
Info:        Working on 3444
Info:            Created 
Info:        Working on 3054
Info:            Created 
Info:        Working on 3055
Info:            Created 
Info:        Working on 3437
Info:            Created 
Info:        Working on 3438
Info:            Created 
Info:        Working on 3244
Info:            Created 
Info:        Working on 3237
Info:            Created 
Info:        Working on 3628
Info:            Created 
Info:        Working on 3434
Info:            Created 
Info:        Working on 3233
Info:            Created 
Info:        Working on 3625
Info:            Created 
Info:        Working on 3623
Info:            Created 
Info:        Working on 3429
Info:            Created 
Info:        Working on 3626
Info:            Created 
Info:        Working on 3224
Info:            Created 
Info:        Working on 3225
Info:            Created 
Info:        Working on 3619
Info:            Created 
Info:        Working on 3620
Info:            Created 
Info:        Working on 3421
Info:            Created 
Info:        Working on 3414
Info:            Created 
Info:        Working on 3807
Info:            Created 
Info:        Working on 3616
Info:            Created 
Info:        Working on 3410
Info:            Created 
Info:        Working on 3804
Info:            Created 
Info:        Working on 3802
Info:            Created 
Info:        Working on 3611
Info:            Created 
Info:        Working on 3805
Info:            Created 
Info:        Working on 3401
Info:            Created 
Info:        Working on 3402
Info:            Created 
Info:        Working on 3798
Info:            Created 
Info:        Working on 3799
Info:            Created 
Info:        Working on 3603
Info:            Created 
Info:        Working on 3596
Info:            Created 
Info:        Working on 3979
Info:            Created 
Info:        Working on 3795
Info:            Created 
Info:        Working on 3592
Info:            Created 
Info:        Working on 3976
Info:            Created 
Info:        Working on 3974
Info:            Created 
Info:        Working on 3790
Info:            Created 
Info:        Working on 3977
Info:            Created 
Info:        Working on 3583
Info:            Created 
Info:        Working on 3584
Info:            Created 
Info:        Working on 3970
Info:            Created 
Info:        Working on 3971
Info:            Created 
Info:        Working on 3782
Info:            Created 
Info:        Working on 3775
Info:            Created 
Info:        Working on 4149
Info:            Created 
Info:        Working on 3967
Info:            Created 
Info:        Working on 3771
Info:            Created 
Info:        Working on 4146
Info:            Created 
Info:        Working on 4144
Info:            Created 
Info:        Working on 3962
Info:            Created 
Info:        Working on 4147
Info:            Created 
Info:        Working on 3762
Info:            Created 
Info:        Working on 3763
Info:            Created 
Info:        Working on 4140
Info:            Created 
Info:        Working on 4141
Info:            Created 
Info:        Working on 3954
Info:            Created 
Info:        Working on 3947
Info:            Created 
Info:        Working on 4326
Info:            Created 
Info:        Working on 4137
Info:            Created 
Info:        Working on 3943
Info:            Created 
Info:        Working on 4323
Info:            Created 
Info:        Working on 4321
Info:            Created 
Info:        Working on 4132
Info:            Created 
Info:        Working on 4324
Info:            Created 
Info:        Working on 3934
Info:            Created 
Info:        Working on 3935
Info:            Created 
Info:        Working on 4317
Info:            Created 
Info:        Working on 4318
Info:            Created 
Info:        Working on 4124
Info:            Created 
Info:        Working on 4117
Info:            Created 
Info:        Working on 4508
Info:            Created 
Info:        Working on 4314
Info:            Created 
Info:        Working on 4113
Info:            Created 
Info:        Working on 4505
Info:            Created 
Info:        Working on 4503
Info:            Created 
Info:        Working on 4309
Info:            Created 
Info:        Working on 4506
Info:            Created 
Info:        Working on 4104
Info:            Created 
Info:        Working on 4105
Info:            Created 
Info:        Working on 4499
Info:            Created 
Info:        Working on 4500
Info:            Created 
Info:        Working on 4301
Info:            Created 
Info:        Working on 4294
Info:            Created 
Info:        Working on 4687
Info:            Created 
Info:        Working on 4496
Info:            Created 
Info:        Working on 4290
Info:            Created 
Info:        Working on 4684
Info:            Created 
Info:        Working on 4682
Info:            Created 
Info:        Working on 4491
Info:            Created 
Info:        Working on 4685
Info:            Created 
Info:        Working on 4281
Info:            Created 
Info:        Working on 4282
Info:            Created 
Info:        Working on 4678
Info:            Created 
Info:        Working on 4679
Info:            Created 
Info:        Working on 4483
Info:            Created 
Info:        Working on 4476
Info:            Created 
Info:        Working on 4859
Info:            Created 
Info:        Working on 4675
Info:            Created 
Info:        Working on 4472
Info:            Created 
Info:        Working on 4856
Info:            Created 
Info:        Working on 4854
Info:            Created 
Info:        Working on 4670
Info:            Created 
Info:        Working on 4857
Info:            Created 
Info:        Working on 4463
Info:            Created 
Info:        Working on 4464
Info:            Created 
Info:        Working on 4850
Info:            Created 
Info:        Working on 4851
Info:            Created 
Info:        Working on 4662
Info:            Created 
Info:        Working on 4655
Info:            Created 
Info:        Working on 5029
Info:            Created 
Info:        Working on 4847
Info:            Created 
Info:        Working on 4651
Info:            Created 
Info:        Working on 5026
Info:            Created 
Info:        Working on 5024
Info:            Created 
Info:        Working on 4842
Info:            Created 
Info:        Working on 5027
Info:            Created 
Info:        Working on 4642
Info:            Created 
Info:        Working on 4643
Info:            Created 
Info:        Working on 5020
Info:            Created 
Info:        Working on 5021
Info:            Created 
Info:        Working on 4834
Info:            Created 
Info:        Working on 4827
Info:            Created 
Info:        Working on 5206
Info:            Created 
Info:        Working on 5017
Info:            Created 
Info:        Working on 4823
Info:            Created 
Info:        Working on 5203
Info:            Created 
Info:        Working on 5201
Info:            Created 
Info:        Working on 5012
Info:            Created 
Info:        Working on 5204
Info:            Created 
Info:        Working on 4814
Info:            Created 
Info:        Working on 4815
Info:            Created 
Info:        Working on 5197
Info:            Created 
Info:        Working on 5198
Info:            Created 
Info:        Working on 5004
Info:            Created 
Info:        Working on 4997
Info:            Created 
Info:        Working on 5388
Info:            Created 
Info:        Working on 5194
Info:            Created 
Info:        Working on 4993
Info:            Created 
Info:        Working on 5385
Info:            Created 
Info:        Working on 5383
Info:            Created 
Info:        Working on 5189
Info:            Created 
Info:        Working on 5386
Info:            Created 
Info:        Working on 4984
Info:            Created 
Info:        Working on 4985
Info:            Created 
Info:        Working on 5379
Info:            Created 
Info:        Working on 5380
Info:            Created 
Info:        Working on 5181
Info:            Created 
Info:        Working on 5174
Info:            Created 
Info:        Working on 5567
Info:            Created 
Info:        Working on 5376
Info:            Created 
Info:        Working on 5170
Info:            Created 
Info:        Working on 5564
Info:            Created 
Info:        Working on 5562
Info:            Created 
Info:        Working on 5371
Info:            Created 
Info:        Working on 5565
Info:            Created 
Info:        Working on 5161
Info:            Created 
Info:        Working on 5162
Info:            Created 
Info:        Working on 5558
Info:            Created 
Info:        Working on 5559
Info:            Created 
Info:        Working on 5363
Info:            Created 
Info:        Working on 5356
Info:            Created 
Info:        Working on 5738
Info:            Created 
Info:        Working on 5555
Info:            Created 
Info:        Working on 5352
Info:            Created 
Info:        Working on 5735
Info:            Created 
Info:        Working on 5733
Info:            Created 
Info:        Working on 5550
Info:            Created 
Info:        Working on 5736
Info:            Created 
Info:        Working on 5343
Info:            Created 
Info:        Working on 5344
Info:            Created 
Info:        Working on 5729
Info:            Created 
Info:        Working on 5730
Info:            Created 
Info:        Working on 5542
Info:            Created 
Info:        Working on 5535
Info:            Created 
Info:        Working on 5906
Info:            Created 
Info:        Working on 5726
Info:            Created 
Info:        Working on 5531
Info:            Created 
Info:        Working on 5903
Info:            Created 
Info:        Working on 5901
Info:            Created 
Info:        Working on 5721
Info:            Created 
Info:        Working on 5904
Info:            Created 
Info:        Working on 5522
Info:            Created 
Info:        Working on 5523
Info:            Created 
Info:        Working on 5897
Info:            Created 
Info:        Working on 5898
Info:            Created 
Info:        Working on 5713
Info:            Created 
Info:        Working on 5706
Info:            Created 
Info:        Working on 6074
Info:            Created 
Info:        Working on 5894
Info:            Created 
Info:        Working on 5702
Info:            Created 
Info:        Working on 6071
Info:            Created 
Info:        Working on 6069
Info:            Created 
Info:        Working on 5889
Info:            Created 
Info:        Working on 6072
Info:            Created 
Info:        Working on 5693
Info:            Created 
Info:        Working on 5694
Info:            Created 
Info:        Working on 6065
Info:            Created 
Info:        Working on 6066
Info:            Created 
Info:        Working on 5881
Info:            Created 
Info:        Working on 5874
Info:            Created 
Info:        Working on 6233
Info:            Created 
Info:        Working on 6062
Info:            Created 
Info:        Working on 5870
Info:            Created 
Info:        Working on 6230
Info:            Created 
Info:        Working on 6228
Info:            Created 
Info:        Working on 6057
Info:            Created 
Info:        Working on 6231
Info:            Created 
Info:        Working on 5861
Info:            Created 
Info:        Working on 5862
Info:            Created 
Info:        Working on 6224
Info:            Created 
Info:        Working on 6225
Info:            Created 
Info:        Working on 6049
Info:            Created 
Info:        Working on 6042
Info:            Created 
Info:        Working on 6358
Info:            Created 
Info:        Working on 6221
Info:            Created 
Info:        Working on 6038
Info:            Created 
Info:        Working on 6355
Info:            Created 
Info:        Working on 6353
Info:            Created 
Info:        Working on 6216
Info:            Created 
Info:        Working on 6356
Info:            Created 
Info:        Working on 6029
Info:            Created 
Info:        Working on 6030
Info:            Created 
Info:        Working on 6349
Info:            Created 
Info:        Working on 6350
Info:            Created 
Info:        Working on 6208
Info:            Created 
Info:        Working on 6201
Info:            Created 
Info:        Working on 6437
Info:            Created 
Info:        Working on 6346
Info:            Created 
Info:        Working on 6197
Info:            Created 
Info:        Working on 6434
Info:            Created 
Info:        Working on 6432
Info:            Created 
Info:        Working on 6341
Info:            Created 
Info:        Working on 6435
Info:            Created 
Info:        Working on 6188
Info:            Created 
Info:        Working on 6189
Info:            Created 
Info:        Working on 6428
Info:            Created 
Info:        Working on 6429
Info:            Created 
Info:        Working on 6333
Info:            Created 
Info:        Working on 6326
Info:            Created 
Info:        Working on 6473
Info:            Created 
Info:        Working on 6425
Info:            Created 
Info:        Working on 6322
Info:            Created 
Info:        Working on 6470
Info:            Created 
Info:        Working on 6468
Info:            Created 
Info:        Working on 6420
Info:            Created 
Info:        Working on 6471
Info:            Created 
Info:        Working on 924
Info:            Created 
Info:        Working on 925
Info:            Created 
Info:        Working on 1080
Info:            Created 
Info:        Working on 1084
Info:            Created 
Info:        Working on 1071
Info:            Created 
Info:        Working on 1072
Info:            Created 
Info:        Working on 1232
Info:            Created 
Info:        Working on 1236
Info:            Created 
Info:        Working on 1223
Info:            Created 
Info:        Working on 1224
Info:            Created 
Info:        Working on 1394
Info:            Created 
Info:        Working on 1398
Info:            Created 
Info:        Working on 1385
Info:            Created 
Info:        Working on 1386
Info:            Created 
Info:        Working on 1570
Info:            Created 
Info:        Working on 1574
Info:            Created 
Info:        Working on 1561
Info:            Created 
Info:        Working on 1562
Info:            Created 
Info:        Working on 1752
Info:            Created 
Info:        Working on 1756
Info:            Created 
Info:        Working on 1743
Info:            Created 
Info:        Working on 1744
Info:            Created 
Info:        Working on 1931
Info:            Created 
Info:        Working on 1935
Info:            Created 
Info:        Working on 1922
Info:            Created 
Info:        Working on 1923
Info:            Created 
Info:        Working on 2103
Info:            Created 
Info:        Working on 2107
Info:            Created 
Info:        Working on 2094
Info:            Created 
Info:        Working on 2095
Info:            Created 
Info:        Working on 2273
Info:            Created 
Info:        Working on 2277
Info:            Created 
Info:        Working on 2264
Info:            Created 
Info:        Working on 2265
Info:            Created 
Info:        Working on 2450
Info:            Created 
Info:        Working on 2454
Info:            Created 
Info:        Working on 2441
Info:            Created 
Info:        Working on 2442
Info:            Created 
Info:        Working on 2632
Info:            Created 
Info:        Working on 2636
Info:            Created 
Info:        Working on 2623
Info:            Created 
Info:        Working on 2624
Info:            Created 
Info:        Working on 2811
Info:            Created 
Info:        Working on 2815
Info:            Created 
Info:        Working on 2802
Info:            Created 
Info:        Working on 2803
Info:            Created 
Info:        Working on 2983
Info:            Created 
Info:        Working on 2987
Info:            Created 
Info:        Working on 2974
Info:            Created 
Info:        Working on 2975
Info:            Created 
Info:        Working on 3153
Info:            Created 
Info:        Working on 3157
Info:            Created 
Info:        Working on 3144
Info:            Created 
Info:        Working on 3145
Info:            Created 
Info:        Working on 3330
Info:            Created 
Info:        Working on 3334
Info:            Created 
Info:        Working on 3321
Info:            Created 
Info:        Working on 3322
Info:            Created 
Info:        Working on 3512
Info:            Created 
Info:        Working on 3516
Info:            Created 
Info:        Working on 3503
Info:            Created 
Info:        Working on 3504
Info:            Created 
Info:        Working on 3691
Info:            Created 
Info:        Working on 3695
Info:            Created 
Info:        Working on 3682
Info:            Created 
Info:        Working on 3683
Info:            Created 
Info:        Working on 3863
Info:            Created 
Info:        Working on 3867
Info:            Created 
Info:        Working on 3854
Info:            Created 
Info:        Working on 3855
Info:            Created 
Info:        Working on 4033
Info:            Created 
Info:        Working on 4037
Info:            Created 
Info:        Working on 4024
Info:            Created 
Info:        Working on 4025
Info:            Created 
Info:        Working on 4210
Info:            Created 
Info:        Working on 4214
Info:            Created 
Info:        Working on 4201
Info:            Created 
Info:        Working on 4202
Info:            Created 
Info:        Working on 4392
Info:            Created 
Info:        Working on 4396
Info:            Created 
Info:        Working on 4383
Info:            Created 
Info:        Working on 4384
Info:            Created 
Info:        Working on 4571
Info:            Created 
Info:        Working on 4575
Info:            Created 
Info:        Working on 4562
Info:            Created 
Info:        Working on 4563
Info:            Created 
Info:        Working on 4743
Info:            Created 
Info:        Working on 4747
Info:            Created 
Info:        Working on 4734
Info:            Created 
Info:        Working on 4735
Info:            Created 
Info:        Working on 4913
Info:            Created 
Info:        Working on 4917
Info:            Created 
Info:        Working on 4904
Info:            Created 
Info:        Working on 4905
Info:            Created 
Info:        Working on 5090
Info:            Created 
Info:        Working on 5094
Info:            Created 
Info:        Working on 5081
Info:            Created 
Info:        Working on 5082
Info:            Created 
Info:        Working on 5272
Info:            Created 
Info:        Working on 5276
Info:            Created 
Info:        Working on 5263
Info:            Created 
Info:        Working on 5264
Info:            Created 
Info:        Working on 5451
Info:            Created 
Info:        Working on 5455
Info:            Created 
Info:        Working on 5442
Info:            Created 
Info:        Working on 5443
Info:            Created 
Info:        Working on 5623
Info:            Created 
Info:        Working on 5627
Info:            Created 
Info:        Working on 5614
Info:            Created 
Info:        Working on 5615
Info:            Created 
Info:        Working on 5792
Info:            Created 
Info:        Working on 5796
Info:            Created 
Info:        Working on 5783
Info:            Created 
Info:        Working on 5784
Info:            Created 
Info:        Working on 5964
Info:            Created 
Info:        Working on 5968
Info:            Created 
Info:        Working on 5955
Info:            Created 
Info:        Working on 5956
Info:            Created 
Info:        Working on 6134
Info:            Created 
Info:        Working on 6138
Info:            Created 
Info:        Working on 6125
Info:            Created 
Info:        Working on 6126
Info:            Created 
Info:        Working on 6277
Info:            Created 
Info:        Working on 6281
Info:            Created 
Info:        Working on 6268
Info:            Created 
Info:        Working on 6269
Info:            Created 
Info:        Working on 6377
Info:            Created 
Info:        Working on 6380
Info:            Created 
Info:        Working on 6096
Info:            Created 
Info:        Working on 6097
Info:            Created 
Info:        Working on 6369
Info:            Created 
Info:        Working on 6247
Info:            Created 
Info:        Working on 5228
Info:            Created 
Info:        Working on 5229
Info:            Created 
Info:        Working on 5580
Info:            Created 
Info:        Working on 5403
Info:            Created 
Info:        Working on 4348
Info:            Created 
Info:        Working on 4349
Info:            Created 
Info:        Working on 4700
Info:            Created 
Info:        Working on 4523
Info:            Created 
Info:        Working on 3468
Info:            Created 
Info:        Working on 3469
Info:            Created 
Info:        Working on 3820
Info:            Created 
Info:        Working on 3643
Info:            Created 
Info:        Working on 2588
Info:            Created 
Info:        Working on 2589
Info:            Created 
Info:        Working on 2940
Info:            Created 
Info:        Working on 2763
Info:            Created 
Info:        Working on 1708
Info:            Created 
Info:        Working on 1709
Info:            Created 
Info:        Working on 2060
Info:            Created 
Info:        Working on 1883
Info:            Created 
Info:        Working on 873
Info:            Created 
Info:        Working on 874
Info:            Created 
Info:        Working on 1183
Info:            Created 
Info:        Working on 1019
Info:            Created 
Info:        Working on 328
Info:            Created 
Info:        Working on 329
Info:            Created 
Info:        Working on 521
Info:            Created 
Info:        Working on 420
Info:            Created 
Info:        Working on 753
Info:            Created 
Info:        Working on 754
Info:            Created 
Info:        Working on 880
Info:            Created 
Info:        Working on 883
Info:            Created 
Info:        Working on 429
Info:            Created 
Info:        Working on 1037
Info:            Created 
Info:        Working on 1187
Info:            Created 
Info:        Working on 528
Info:            Created 
Info:        Working on 1189
Info:            Created 
Info:        Working on 634
Info:            Created 
Info:        Working on 1036
Info:            Created 
Info:        Working on 755
Info:            Created 
Info:        Working on 890
Info:            Created 
Info:        Working on 82
Info:            Created 
Info:        Working on 422
Info:            Created 
Info:        Working on 423
Info:            Created 
Info:        Working on 102
Info:            Created 
Info:        Working on 519
Info:            Created 
Info:        Working on 126
Info:            Created 
Info:        Working on 620
Info:            Created 
Info:        Working on 165
Info:            Created 
Info:        Working on 225
Info:            Created 
Info:        Working on 308
Info:            Created 
Info:        Working on 1021
Info:            Created 
Info:        Working on 1022
Info:            Created 
Info:        Working on 409
Info:            Created 
Info:        Working on 1181
Info:            Created 
Info:        Working on 512
Info:            Created 
Info:        Working on 1350
Info:            Created 
Info:        Working on 613
Info:            Created 
Info:        Working on 723
Info:            Created 
Info:        Working on 855
Info:            Created 
Info:        Working on 1885
Info:            Created 
Info:        Working on 1886
Info:            Created 
Info:        Working on 1008
Info:            Created 
Info:        Working on 2058
Info:            Created 
Info:        Working on 1174
Info:            Created 
Info:        Working on 2230
Info:            Created 
Info:        Working on 1343
Info:            Created 
Info:        Working on 1513
Info:            Created 
Info:        Working on 1690
Info:            Created 
Info:        Working on 2765
Info:            Created 
Info:        Working on 2766
Info:            Created 
Info:        Working on 1872
Info:            Created 
Info:        Working on 2938
Info:            Created 
Info:        Working on 2051
Info:            Created 
Info:        Working on 3110
Info:            Created 
Info:        Working on 2223
Info:            Created 
Info:        Working on 2393
Info:            Created 
Info:        Working on 2570
Info:            Created 
Info:        Working on 3645
Info:            Created 
Info:        Working on 3646
Info:            Created 
Info:        Working on 2752
Info:            Created 
Info:        Working on 3818
Info:            Created 
Info:        Working on 2931
Info:            Created 
Info:        Working on 3990
Info:            Created 
Info:        Working on 3103
Info:            Created 
Info:        Working on 3273
Info:            Created 
Info:        Working on 3450
Info:            Created 
Info:        Working on 4525
Info:            Created 
Info:        Working on 4526
Info:            Created 
Info:        Working on 3632
Info:            Created 
Info:        Working on 4698
Info:            Created 
Info:        Working on 3811
Info:            Created 
Info:        Working on 4870
Info:            Created 
Info:        Working on 3983
Info:            Created 
Info:        Working on 4153
Info:            Created 
Info:        Working on 4330
Info:            Created 
Info:        Working on 5405
Info:            Created 
Info:        Working on 5406
Info:            Created 
Info:        Working on 4512
Info:            Created 
Info:        Working on 5578
Info:            Created 
Info:        Working on 4691
Info:            Created 
Info:        Working on 5749
Info:            Created 
Info:        Working on 4863
Info:            Created 
Info:        Working on 5033
Info:            Created 
Info:        Working on 5210
Info:            Created 
Info:        Working on 6249
Info:            Created 
Info:        Working on 6250
Info:            Created 
Info:        Working on 5392
Info:            Created 
Info:        Working on 6367
Info:            Created 
Info:        Working on 5571
Info:            Created 
Info:        Working on 6442
Info:            Created 
Info:        Working on 5742
Info:            Created 
Info:        Working on 5910
Info:            Created 
Info:        Working on 6078
Info:            Created 
Info:        Working on 6455
Info:            Created 
Info:        Working on 6456
Info:            Created 
Info:        Working on 6236
Info:            Created 
Info:        Working on 6481
Info:            Created 
Info:        Working on 6361
Info:            Created 
Info:        Working on 6479
Info:            Created 
Info:        Working on 6440
Info:            Created 
Info:        Working on 6449
Info:            Created 
Info:        Working on 6477
Info:            Created 
Info:        Working on 6402
Info:            Created 
Info:        Working on 6403
Info:            Created 
Info:        Working on 6288
Info:            Created 
Info:        Working on 6463
Info:            Created 
Info:        Working on 6399
Info:            Created 
Info:        Working on 6461
Info:            Created 
Info:        Working on 6464
Info:            Created 
Info:        Working on 6393
Info:            Created 
Info:        Working on 6459
Info:            Created 
Info:        Working on 6304
Info:            Created 
Info:        Working on 6305
Info:            Created 
Info:        Working on 6145
Info:            Created 
Info:        Working on 6410
Info:            Created 
Info:        Working on 6301
Info:            Created 
Info:        Working on 6408
Info:            Created 
Info:        Working on 6411
Info:            Created 
Info:        Working on 6295
Info:            Created 
Info:        Working on 6406
Info:            Created 
Info:        Working on 6161
Info:            Created 
Info:        Working on 6162
Info:            Created 
Info:        Working on 5975
Info:            Created 
Info:        Working on 6312
Info:            Created 
Info:        Working on 6158
Info:            Created 
Info:        Working on 6310
Info:            Created 
Info:        Working on 6313
Info:            Created 
Info:        Working on 6152
Info:            Created 
Info:        Working on 6308
Info:            Created 
Info:        Working on 5991
Info:            Created 
Info:        Working on 5992
Info:            Created 
Info:        Working on 5803
Info:            Created 
Info:        Working on 6169
Info:            Created 
Info:        Working on 5988
Info:            Created 
Info:        Working on 6167
Info:            Created 
Info:        Working on 6170
Info:            Created 
Info:        Working on 5982
Info:            Created 
Info:        Working on 6165
Info:            Created 
Info:        Working on 5819
Info:            Created 
Info:        Working on 5820
Info:            Created 
Info:        Working on 5634
Info:            Created 
Info:        Working on 5999
Info:            Created 
Info:        Working on 5816
Info:            Created 
Info:        Working on 5997
Info:            Created 
Info:        Working on 6000
Info:            Created 
Info:        Working on 5810
Info:            Created 
Info:        Working on 5995
Info:            Created 
Info:        Working on 5650
Info:            Created 
Info:        Working on 5651
Info:            Created 
Info:        Working on 5462
Info:            Created 
Info:        Working on 5827
Info:            Created 
Info:        Working on 5647
Info:            Created 
Info:        Working on 5825
Info:            Created 
Info:        Working on 5828
Info:            Created 
Info:        Working on 5641
Info:            Created 
Info:        Working on 5823
Info:            Created 
Info:        Working on 5478
Info:            Created 
Info:        Working on 5479
Info:            Created 
Info:        Working on 5283
Info:            Created 
Info:        Working on 5658
Info:            Created 
Info:        Working on 5475
Info:            Created 
Info:        Working on 5656
Info:            Created 
Info:        Working on 5659
Info:            Created 
Info:        Working on 5469
Info:            Created 
Info:        Working on 5654
Info:            Created 
Info:        Working on 5299
Info:            Created 
Info:        Working on 5300
Info:            Created 
Info:        Working on 5101
Info:            Created 
Info:        Working on 5486
Info:            Created 
Info:        Working on 5296
Info:            Created 
Info:        Working on 5484
Info:            Created 
Info:        Working on 5487
Info:            Created 
Info:        Working on 5290
Info:            Created 
Info:        Working on 5482
Info:            Created 
Info:        Working on 5117
Info:            Created 
Info:        Working on 5118
Info:            Created 
Info:        Working on 4924
Info:            Created 
Info:        Working on 5307
Info:            Created 
Info:        Working on 5114
Info:            Created 
Info:        Working on 5305
Info:            Created 
Info:        Working on 5308
Info:            Created 
Info:        Working on 5108
Info:            Created 
Info:        Working on 5303
Info:            Created 
Info:        Working on 4940
Info:            Created 
Info:        Working on 4941
Info:            Created 
Info:        Working on 4754
Info:            Created 
Info:        Working on 5125
Info:            Created 
Info:        Working on 4937
Info:            Created 
Info:        Working on 5123
Info:            Created 
Info:        Working on 5126
Info:            Created 
Info:        Working on 4931
Info:            Created 
Info:        Working on 5121
Info:            Created 
Info:        Working on 4770
Info:            Created 
Info:        Working on 4771
Info:            Created 
Info:        Working on 4582
Info:            Created 
Info:        Working on 4948
Info:            Created 
Info:        Working on 4767
Info:            Created 
Info:        Working on 4946
Info:            Created 
Info:        Working on 4949
Info:            Created 
Info:        Working on 4761
Info:            Created 
Info:        Working on 4944
Info:            Created 
Info:        Working on 4598
Info:            Created 
Info:        Working on 4599
Info:            Created 
Info:        Working on 4403
Info:            Created 
Info:        Working on 4778
Info:            Created 
Info:        Working on 4595
Info:            Created 
Info:        Working on 4776
Info:            Created 
Info:        Working on 4779
Info:            Created 
Info:        Working on 4589
Info:            Created 
Info:        Working on 4774
Info:            Created 
Info:        Working on 4419
Info:            Created 
Info:        Working on 4420
Info:            Created 
Info:        Working on 4221
Info:            Created 
Info:        Working on 4606
Info:            Created 
Info:        Working on 4416
Info:            Created 
Info:        Working on 4604
Info:            Created 
Info:        Working on 4607
Info:            Created 
Info:        Working on 4410
Info:            Created 
Info:        Working on 4602
Info:            Created 
Info:        Working on 4237
Info:            Created 
Info:        Working on 4238
Info:            Created 
Info:        Working on 4044
Info:            Created 
Info:        Working on 4427
Info:            Created 
Info:        Working on 4234
Info:            Created 
Info:        Working on 4425
Info:            Created 
Info:        Working on 4428
Info:            Created 
Info:        Working on 4228
Info:            Created 
Info:        Working on 4423
Info:            Created 
Info:        Working on 4060
Info:            Created 
Info:        Working on 4061
Info:            Created 
Info:        Working on 3874
Info:            Created 
Info:        Working on 4245
Info:            Created 
Info:        Working on 4057
Info:            Created 
Info:        Working on 4243
Info:            Created 
Info:        Working on 4246
Info:            Created 
Info:        Working on 4051
Info:            Created 
Info:        Working on 4241
Info:            Created 
Info:        Working on 3890
Info:            Created 
Info:        Working on 3891
Info:            Created 
Info:        Working on 3702
Info:            Created 
Info:        Working on 4068
Info:            Created 
Info:        Working on 3887
Info:            Created 
Info:        Working on 4066
Info:            Created 
Info:        Working on 4069
Info:            Created 
Info:        Working on 3881
Info:            Created 
Info:        Working on 4064
Info:            Created 
Info:        Working on 3718
Info:            Created 
Info:        Working on 3719
Info:            Created 
Info:        Working on 3523
Info:            Created 
Info:        Working on 3898
Info:            Created 
Info:        Working on 3715
Info:            Created 
Info:        Working on 3896
Info:            Created 
Info:        Working on 3899
Info:            Created 
Info:        Working on 3709
Info:            Created 
Info:        Working on 3894
Info:            Created 
Info:        Working on 3539
Info:            Created 
Info:        Working on 3540
Info:            Created 
Info:        Working on 3341
Info:            Created 
Info:        Working on 3726
Info:            Created 
Info:        Working on 3536
Info:            Created 
Info:        Working on 3724
Info:            Created 
Info:        Working on 3727
Info:            Created 
Info:        Working on 3530
Info:            Created 
Info:        Working on 3722
Info:            Created 
Info:        Working on 3357
Info:            Created 
Info:        Working on 3358
Info:            Created 
Info:        Working on 3164
Info:            Created 
Info:        Working on 3547
Info:            Created 
Info:        Working on 3354
Info:            Created 
Info:        Working on 3545
Info:            Created 
Info:        Working on 3548
Info:            Created 
Info:        Working on 3348
Info:            Created 
Info:        Working on 3543
Info:            Created 
Info:        Working on 3180
Info:            Created 
Info:        Working on 3181
Info:            Created 
Info:        Working on 2994
Info:            Created 
Info:        Working on 3365
Info:            Created 
Info:        Working on 3177
Info:            Created 
Info:        Working on 3363
Info:            Created 
Info:        Working on 3366
Info:            Created 
Info:        Working on 3171
Info:            Created 
Info:        Working on 3361
Info:            Created 
Info:        Working on 3010
Info:            Created 
Info:        Working on 3011
Info:            Created 
Info:        Working on 2822
Info:            Created 
Info:        Working on 3188
Info:            Created 
Info:        Working on 3007
Info:            Created 
Info:        Working on 3186
Info:            Created 
Info:        Working on 3189
Info:            Created 
Info:        Working on 3001
Info:            Created 
Info:        Working on 3184
Info:            Created 
Info:        Working on 2838
Info:            Created 
Info:        Working on 2839
Info:            Created 
Info:        Working on 2643
Info:            Created 
Info:        Working on 3018
Info:            Created 
Info:        Working on 2835
Info:            Created 
Info:        Working on 3016
Info:            Created 
Info:        Working on 3019
Info:            Created 
Info:        Working on 2829
Info:            Created 
Info:        Working on 3014
Info:            Created 
Info:        Working on 2659
Info:            Created 
Info:        Working on 2660
Info:            Created 
Info:        Working on 2461
Info:            Created 
Info:        Working on 2846
Info:            Created 
Info:        Working on 2656
Info:            Created 
Info:        Working on 2844
Info:            Created 
Info:        Working on 2847
Info:            Created 
Info:        Working on 2650
Info:            Created 
Info:        Working on 2842
Info:            Created 
Info:        Working on 2477
Info:            Created 
Info:        Working on 2478
Info:            Created 
Info:        Working on 2284
Info:            Created 
Info:        Working on 2667
Info:            Created 
Info:        Working on 2474
Info:            Created 
Info:        Working on 2665
Info:            Created 
Info:        Working on 2668
Info:            Created 
Info:        Working on 2468
Info:            Created 
Info:        Working on 2663
Info:            Created 
Info:        Working on 2300
Info:            Created 
Info:        Working on 2301
Info:            Created 
Info:        Working on 2114
Info:            Created 
Info:        Working on 2485
Info:            Created 
Info:        Working on 2297
Info:            Created 
Info:        Working on 2483
Info:            Created 
Info:        Working on 2486
Info:            Created 
Info:        Working on 2291
Info:            Created 
Info:        Working on 2481
Info:            Created 
Info:        Working on 2130
Info:            Created 
Info:        Working on 2131
Info:            Created 
Info:        Working on 1942
Info:            Created 
Info:        Working on 2308
Info:            Created 
Info:        Working on 2127
Info:            Created 
Info:        Working on 2306
Info:            Created 
Info:        Working on 2309
Info:            Created 
Info:        Working on 2121
Info:            Created 
Info:        Working on 2304
Info:            Created 
Info:        Working on 1958
Info:            Created 
Info:        Working on 1959
Info:            Created 
Info:        Working on 1763
Info:            Created 
Info:        Working on 2138
Info:            Created 
Info:        Working on 1955
Info:            Created 
Info:        Working on 2136
Info:            Created 
Info:        Working on 2139
Info:            Created 
Info:        Working on 1949
Info:            Created 
Info:        Working on 2134
Info:            Created 
Info:        Working on 1779
Info:            Created 
Info:        Working on 1780
Info:            Created 
Info:        Working on 1581
Info:            Created 
Info:        Working on 1966
Info:            Created 
Info:        Working on 1776
Info:            Created 
Info:        Working on 1964
Info:            Created 
Info:        Working on 1967
Info:            Created 
Info:        Working on 1770
Info:            Created 
Info:        Working on 1962
Info:            Created 
Info:        Working on 1597
Info:            Created 
Info:        Working on 1598
Info:            Created 
Info:        Working on 1405
Info:            Created 
Info:        Working on 1787
Info:            Created 
Info:        Working on 1594
Info:            Created 
Info:        Working on 1785
Info:            Created 
Info:        Working on 1788
Info:            Created 
Info:        Working on 1588
Info:            Created 
Info:        Working on 1783
Info:            Created 
Info:        Working on 1421
Info:            Created 
Info:        Working on 1422
Info:            Created 
Info:        Working on 1243
Info:            Created 
Info:        Working on 1605
Info:            Created 
Info:        Working on 1418
Info:            Created 
Info:        Working on 1603
Info:            Created 
Info:        Working on 1606
Info:            Created 
Info:        Working on 1412
Info:            Created 
Info:        Working on 1601
Info:            Created 
Info:        Working on 1259
Info:            Created 
Info:        Working on 1260
Info:            Created 
Info:        Working on 1091
Info:            Created 
Info:        Working on 1429
Info:            Created 
Info:        Working on 1256
Info:            Created 
Info:        Working on 1427
Info:            Created 
Info:        Working on 1430
Info:            Created 
Info:        Working on 1250
Info:            Created 
Info:        Working on 1425
Info:            Created 
Info:        Created 
Info:    Working on BRep 0
Info:        Using 3D tolerance 1.11867e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Finished with 
Info:    Points:                 0 found       0 created       0 failed
Info:    Coordinate Systems      0 found       0 created       0 failed
Info:    Curves:                 0 found       0 created       0 failed
Info:    Surfaces:               0 found       0 created       0 failed
Info:    Trimmed Surfaces:       0 found       0 created       0 failed
Info:    Breps:                  1 found       1 created       0 failed
Finished logging messages at Sat Aug 30 06:38:08 2014
